#!/usr/bin/env bash

# 16-node variant of arm_roce_8node.sh.
# Generated by adapting scripts/arm_roce_8node.sh: NODE0..NODE15 IPs,
# write_config emits 18 lines, detect_local_node scans 16 IPs,
# CMake is configured with -DCOTRA_MACHINE_NUM=16.

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
REPO_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd -P)

MODE="check"
DATASET_DIR="/home/team/alg_mathlib/c30061081/dataset/gist_1M_960"
OUTPUT_DIR=""
BUILD_DIR=""
BASE_FILE=""
QUERY_FILE=""
GT_FILE=""
DATA_TYPE="float"
DISTANCE="l2"
NODE0_RDMA_IP="${NODE0_RDMA_IP:-33.40.10.121}"
NODE1_RDMA_IP="${NODE1_RDMA_IP:-}"
NODE2_RDMA_IP="${NODE2_RDMA_IP:-}"
NODE3_RDMA_IP="${NODE3_RDMA_IP:-}"
NODE4_RDMA_IP="${NODE4_RDMA_IP:-}"
NODE5_RDMA_IP="${NODE5_RDMA_IP:-}"
NODE6_RDMA_IP="${NODE6_RDMA_IP:-}"
NODE7_RDMA_IP="${NODE7_RDMA_IP:-}"
NODE8_RDMA_IP="${NODE8_RDMA_IP:-}"
NODE9_RDMA_IP="${NODE9_RDMA_IP:-}"
NODE10_RDMA_IP="${NODE10_RDMA_IP:-}"
NODE11_RDMA_IP="${NODE11_RDMA_IP:-}"
NODE12_RDMA_IP="${NODE12_RDMA_IP:-}"
NODE13_RDMA_IP="${NODE13_RDMA_IP:-}"
NODE14_RDMA_IP="${NODE14_RDMA_IP:-}"
NODE15_RDMA_IP="${NODE15_RDMA_IP:-}"
MAX_THREAD_NUM="${MAX_THREAD_NUM:-128}"
LEADER_IP="${LEADER_IP:-71.54.52.21}"
MEMCACHED_PORT="${MEMCACHED_PORT:-18516}"
RDMA_DEVICE="${RDMA_DEVICE:-mlx5_0}"
IB_PORT="${IB_PORT:-1}"
GID_INDEX="${GID_INDEX:-}"
THREADS="${THREADS:-8}"
INDEX_THREADS="${INDEX_THREADS:-$THREADS}"
RDMA_THREADS="${RDMA_THREADS:-$THREADS}"
BUILD_JOBS="${BUILD_JOBS:-24}"
ENABLE_LAT="${ENABLE_LAT:-0}"
BARRIER_TIMEOUT="${BARRIER_TIMEOUT:-1800}"
SEARCH_DRAM_GB="${SEARCH_DRAM_GB:-16}"
BUILD_DRAM_GB="${BUILD_DRAM_GB:-64}"
MAX_DEGREE="${MAX_DEGREE:-48}"
BUILD_L="${BUILD_L:-500}"
RESULT_K="${RESULT_K:-10}"
# 方法选择：cotra|shard|kshard|single|global (见 arm_roce_8node.sh 注释)
APP_MODE="${APP_MODE:-cotra}"
APP_TYPE="${APP_TYPE:-scala_v3}"
GRAPH_TYPE="${GRAPH_TYPE:-scalagraph_v3}"
DEPS_DIR="${DEPS_DIR:-}"
LOCAL_NODE_ID=""
CMAKE_BIN=""
CC_BIN=""
CXX_BIN=""
CXX_COMPAT_FLAGS=()
CONFIG_FILE=""
BASE_ROWS=0
BASE_DIM=0
QUERY_ROWS=0
QUERY_DIM=0
GT_ROWS=0
GT_K=0
MILLION=0
RESULT_QSIZE=""

NUM_NODES=16
ALL_NODE_IPS=()

usage() {
  printf '%s\n' \
    "Usage:" \
    "  NODE1_RDMA_IP=<ip1> ... NODE15_RDMA_IP=<ip15> bash scripts/arm_roce_16node.sh <mode> [options]" \
    "" \
    "Modes:" \
    "  check    Check toolchain, headers, RDMA, routes, dataset, and shared path." \
    "  build    Run check, configure CMake for 16 nodes, and compile." \
    "  index    Run the distributed index build across 16 nodes." \
    "  search   Search the completed index across 16 nodes." \
    "" \
    "Important options:" \
    "  --node0-rdma-ip IP .. --node15-rdma-ip IP  RoCE IPs for the 16 nodes." \
    "  --leader-ip IP       Memcached address (usually node 0)." \
    "  --dataset-dir PATH   Default: ${DATASET_DIR}" \
    "  --base-file PATH     Override automatic base bin discovery." \
    "  --query-file PATH    Override automatic query bin discovery." \
    "  --gt-file PATH       Override automatic GT bin discovery." \
    "  --output-dir PATH    Shared index directory (must be visible on all nodes)." \
    "  --build-dir PATH     Per-host CMake build directory." \
    "  --threads N          Set both index and RDMA threads (legacy)." \
    "  --index-threads N    DiskANN/OpenMP build threads. Default: 8" \
    "  --rdma-threads N     CoTra/RDMA worker threads. Default: 8" \
    "  --max-threads N      Compile-time thread array size cap. Default: 128" \
    "  --max-degree R       Graph max out-degree (M/R). 8node default: 48" \
    "  --build-l L          Build queue size / efC. 8node default: 500" \
    "  --search-dram-gb GB  Search-stage DRAM cap / -B.  Default: 16" \
    "  --build-dram-gb GB   Build-stage DRAM cap / -M.   Default: 64" \
    "  --query-size N       Search query count. Default: auto from file header" \
    "  --res-knn K          Recall@K target. Default: 10" \
    "  --build-jobs N       Parallel compile jobs. Default: 24" \
    "  --gid-index N        Override automatic RoCE GID selection." \
    "  --deps-dir PATH      Shared dir with include/lib64 copied from a healthy" \
    "                       node (e.g. shared_deps: include/ + lib64/ subdirs)." \
    "  --help               Show this message." \
    "" \
    "Start node 0 first on every mode, then nodes 1..15."
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

warn() {
  printf 'WARN: %s\n' "$*" >&2
}

note() {
  printf '\n=== %s ===\n' "$*"
}

is_positive_integer() {
  [[ $1 =~ ^[1-9][0-9]*$ ]]
}

is_nonnegative_integer() {
  [[ $1 =~ ^[0-9]+$ ]]
}

is_ipv4() {
  local ip=$1
  local a b c d extra
  IFS=. read -r a b c d extra <<<"${ip}"
  [[ -z ${extra:-} && -n ${a:-} && -n ${b:-} && -n ${c:-} && -n ${d:-} ]] ||
    return 1
  for part in "$a" "$b" "$c" "$d"; do
    [[ $part =~ ^[0-9]+$ ]] || return 1
    ((10#$part >= 0 && 10#$part <= 255)) || return 1
  done
}

while (($# > 0)); do
  case "$1" in
    check|build|index|search)
      MODE=$1
      shift
      ;;
    --node0-rdma-ip)
      NODE0_RDMA_IP=${2:?missing value for --node0-rdma-ip}
      shift 2
      ;;
    --node1-rdma-ip)
      NODE1_RDMA_IP=${2:?missing value for --node1-rdma-ip}
      shift 2
      ;;
    --node2-rdma-ip)
      NODE2_RDMA_IP=${2:?missing value for --node2-rdma-ip}
      shift 2
      ;;
    --node3-rdma-ip)
      NODE3_RDMA_IP=${2:?missing value for --node3-rdma-ip}
      shift 2
      ;;
    --node4-rdma-ip)
      NODE4_RDMA_IP=${2:?missing value for --node4-rdma-ip}
      shift 2
      ;;
    --node5-rdma-ip)
      NODE5_RDMA_IP=${2:?missing value for --node5-rdma-ip}
      shift 2
      ;;
    --node6-rdma-ip)
      NODE6_RDMA_IP=${2:?missing value for --node6-rdma-ip}
      shift 2
      ;;
    --node7-rdma-ip)
      NODE7_RDMA_IP=${2:?missing value for --node7-rdma-ip}
      shift 2
      ;;
    --node8-rdma-ip)
      NODE8_RDMA_IP=${2:?missing value for --node8-rdma-ip}
      shift 2
      ;;
    --node9-rdma-ip)
      NODE9_RDMA_IP=${2:?missing value for --node9-rdma-ip}
      shift 2
      ;;
    --node10-rdma-ip)
      NODE10_RDMA_IP=${2:?missing value for --node10-rdma-ip}
      shift 2
      ;;
    --node11-rdma-ip)
      NODE11_RDMA_IP=${2:?missing value for --node11-rdma-ip}
      shift 2
      ;;
    --node12-rdma-ip)
      NODE12_RDMA_IP=${2:?missing value for --node12-rdma-ip}
      shift 2
      ;;
    --node13-rdma-ip)
      NODE13_RDMA_IP=${2:?missing value for --node13-rdma-ip}
      shift 2
      ;;
    --node14-rdma-ip)
      NODE14_RDMA_IP=${2:?missing value for --node14-rdma-ip}
      shift 2
      ;;
    --node15-rdma-ip)
      NODE15_RDMA_IP=${2:?missing value for --node15-rdma-ip}
      shift 2
      ;;
    --max-threads)
      MAX_THREAD_NUM=${2:?missing value for --max-threads}
      shift 2
      ;;
    --leader-ip)
      LEADER_IP=${2:?missing value for --leader-ip}
      shift 2
      ;;
    --memcached-port)
      MEMCACHED_PORT=${2:?missing value for --memcached-port}
      shift 2
      ;;
    --dataset-dir)
      DATASET_DIR=${2:?missing value for --dataset-dir}
      shift 2
      ;;
    --base-file)
      BASE_FILE=${2:?missing value for --base-file}
      shift 2
      ;;
    --query-file)
      QUERY_FILE=${2:?missing value for --query-file}
      shift 2
      ;;
    --gt-file)
      GT_FILE=${2:?missing value for --gt-file}
      shift 2
      ;;
    --output-dir)
      OUTPUT_DIR=${2:?missing value for --output-dir}
      shift 2
      ;;
    --build-dir)
      BUILD_DIR=${2:?missing value for --build-dir}
      shift 2
      ;;
    --threads)
      THREADS=${2:?missing value for --threads}
      INDEX_THREADS=$THREADS
      RDMA_THREADS=$THREADS
      shift 2
      ;;
    --index-threads)
      INDEX_THREADS=${2:?missing value for --index-threads}
      shift 2
      ;;
    --rdma-threads)
      RDMA_THREADS=${2:?missing value for --rdma-threads}
      shift 2
      ;;
    --build-jobs)
      BUILD_JOBS=${2:?missing value for --build-jobs}
      shift 2
      ;;
    --gid-index)
      GID_INDEX=${2:?missing value for --gid-index}
      shift 2
      ;;
    --device)
      RDMA_DEVICE=${2:?missing value for --device}
      shift 2
      ;;
    --ib-port)
      IB_PORT=${2:?missing value for --ib-port}
      shift 2
      ;;
    --deps-dir)
      DEPS_DIR=${2:?missing value for --deps-dir}
      shift 2
      ;;
    --lat)
      ENABLE_LAT=1
      shift 1
      ;;
    --max-threads)
      MAX_THREAD_NUM=${2:?missing value for --max-threads}
      shift 2
      ;;
    --max-degree)
      MAX_DEGREE=${2:?missing value for --max-degree}
      shift 2
      ;;
    --build-l)
      BUILD_L=${2:?missing value for --build-l}
      shift 2
      ;;
    --search-dram-gb)
      SEARCH_DRAM_GB=${2:?missing value for --search-dram-gb}
      shift 2
      ;;
    --build-dram-gb)
      BUILD_DRAM_GB=${2:?missing value for --build-dram-gb}
      shift 2
      ;;
    --query-size)
      RESULT_QSIZE=${2:?missing value for --query-size}
      shift 2
      ;;
    --res-knn)
      RESULT_K=${2:?missing value for --res-knn}
      shift 2
      ;;
    --app-mode)
      APP_MODE=${2:?missing value for --app-mode}
      case "$APP_MODE" in
        cotra)   APP_TYPE="scala_v3";        GRAPH_TYPE="scalagraph_v3" ;;
        shard)   APP_TYPE="b2";              GRAPH_TYPE="shared_nothing" ;;
        kshard)  APP_TYPE="b2kmeansbatch";   GRAPH_TYPE="shared_nothing" ;;
        single)  APP_TYPE="single";          GRAPH_TYPE="vamana" ;;
        global)  APP_TYPE="single";          GRAPH_TYPE="vamana" ;;
        *) die "unknown --app-mode: $APP_MODE (cotra|shard|kshard|single|global)" ;;
      esac
      shift 2
      ;;
    --app-type)
      APP_TYPE=${2:?missing value for --app-type}
      shift 2
      ;;
    --graph-type)
      GRAPH_TYPE=${2:?missing value for --graph-type}
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

HOST_SHORT=$(hostname -s 2>/dev/null || hostname)
if [[ -z $BUILD_DIR ]]; then
  BUILD_DIR="${REPO_ROOT}/build-arm-16node-${HOST_SHORT}"
fi
if [[ -z $OUTPUT_DIR ]]; then
  OUTPUT_DIR="${DATASET_DIR}/cotra_16node_index"
fi
CONFIG_FILE="${BUILD_DIR}/cotra_16node.conf"

ALL_NODE_IPS=(
  "$NODE0_RDMA_IP" "$NODE1_RDMA_IP" "$NODE2_RDMA_IP" "$NODE3_RDMA_IP"
  "$NODE4_RDMA_IP" "$NODE5_RDMA_IP" "$NODE6_RDMA_IP" "$NODE7_RDMA_IP"
  "$NODE8_RDMA_IP" "$NODE9_RDMA_IP" "$NODE10_RDMA_IP" "$NODE11_RDMA_IP"
  "$NODE12_RDMA_IP" "$NODE13_RDMA_IP" "$NODE14_RDMA_IP" "$NODE15_RDMA_IP"
)

# If --deps-dir was given (or DEPS_DIR env var), prepend its include/lib path
# hints to the calling environment, and make sure any helper binaries we
# shipped (nc, memcached fallbacks) are visible on PATH before any tool is
# invoked. This is done BEFORE validate_arguments / find_toolchain so that
# check_headers, probe_memcached, configure, and the built binaries all agree
# on the same dependency layout.
if [[ -n $DEPS_DIR ]]; then
  if [[ -d ${DEPS_DIR}/bin ]]; then
    export PATH="${DEPS_DIR}/bin${PATH:+:${PATH}}"
  fi
  # Help toolchain discovery find extra compilers / cmake if the deps dir
  # carries them (harmless when absent).
  if [[ -d ${DEPS_DIR}/sbin ]]; then
    export PATH="${DEPS_DIR}/sbin${PATH:+:${PATH}}"
  fi
fi

validate_arguments() {
  local i j
  for i in "${!ALL_NODE_IPS[@]}"; do
    [[ -n ${ALL_NODE_IPS[$i]} ]] ||
      die "node $i RoCE IP is required; use --node${i}-rdma-ip or NODE${i}_RDMA_IP"
    is_ipv4 "${ALL_NODE_IPS[$i]}" ||
      die "invalid node $i RoCE IP: ${ALL_NODE_IPS[$i]}"
  done
  is_ipv4 "$LEADER_IP" || die "invalid leader IP: ${LEADER_IP}"

  # 任意两个 IP 不能相等
  for i in "${!ALL_NODE_IPS[@]}"; do
    for j in "${!ALL_NODE_IPS[@]}"; do
      ((j > i)) || continue
      [[ ${ALL_NODE_IPS[$i]} != "${ALL_NODE_IPS[$j]}" ]] ||
        die "node $i and node $j share the same RoCE IP ${ALL_NODE_IPS[$i]}"
    done
  done

  for pair in \
    "index threads:${INDEX_THREADS}" \
    "RDMA threads:${RDMA_THREADS}" \
    "max thread cap:${MAX_THREAD_NUM}" \
    "build jobs:${BUILD_JOBS}" \
    "memcached port:${MEMCACHED_PORT}" \
    "IB port:${IB_PORT}" \
    "barrier timeout:${BARRIER_TIMEOUT}"; do
    local name=${pair%%:*}
    local value=${pair#*:}
    is_positive_integer "$value" || die "${name} must be a positive integer"
  done
  ((MEMCACHED_PORT <= 65535)) || die "memcached port is too large"
  ((INDEX_THREADS <= MAX_THREAD_NUM)) || die "index threads must not exceed MAX_THREAD_NUM=${MAX_THREAD_NUM}"
  ((RDMA_THREADS <= MAX_THREAD_NUM)) ||
    die "RDMA threads must not exceed MAX_THREAD_NUM=${MAX_THREAD_NUM}"
  if [[ -n $GID_INDEX ]]; then
    is_nonnegative_integer "$GID_INDEX" || die "GID index must be non-negative"
  fi
  [[ $DATA_TYPE == float ]] || die "this GIST script currently expects float vectors"
  [[ $DISTANCE == l2 ]] || die "this GIST script currently expects L2 distance"
  if [[ -n $DEPS_DIR ]]; then
    [[ -d $DEPS_DIR ]] || die "--deps-dir does not exist: ${DEPS_DIR}"
    [[ -d ${DEPS_DIR}/include ]] || die "--deps-dir is missing ${DEPS_DIR}/include subdirectory"
    mkdir -p "${DEPS_DIR}/lib64" 2>/dev/null || true
  fi
}

has_local_ipv4() {
  ip -4 -o addr show | awk '{print $4}' | cut -d/ -f1 | grep -Fqx -- "$1"
}

detect_local_node() {
  command -v ip >/dev/null 2>&1 || die "the ip command is not installed"
  local match_cnt=0
  local i
  for i in "${!ALL_NODE_IPS[@]}"; do
    if has_local_ipv4 "${ALL_NODE_IPS[$i]}"; then
      LOCAL_NODE_ID=$i
      match_cnt=$((match_cnt + 1))
    fi
  done
  if ((match_cnt != 1)); then
    printf 'Configured node addresses:\n' >&2
    for i in "${!ALL_NODE_IPS[@]}"; do
      printf '  node %s: %s\n' "$i" "${ALL_NODE_IPS[$i]}" >&2
    done
    printf 'Local IPv4 addresses:\n' >&2
    ip -4 -o addr show >&2
    die "exactly one configured RoCE IP must exist on this host (matched ${match_cnt})"
  fi
}

write_config() {
  mkdir -p "$BUILD_DIR"
  {
    printf '%s\n' "$LEADER_IP"
    printf '%s\n' "$MEMCACHED_PORT"
    local i
    for i in "${!ALL_NODE_IPS[@]}"; do
      printf '%s=%s\n' "${ALL_NODE_IPS[$i]}" "$i"
    done
  } >"$CONFIG_FILE"
}

version_at_least() {
  local actual=$1
  local required_major=$2
  local required_minor=$3
  local major minor rest
  IFS=. read -r major minor rest <<<"${actual}"
  [[ ${major:-} =~ ^[0-9]+$ && ${minor:-0} =~ ^[0-9]+$ ]] || return 1
  ((major > required_major ||
    (major == required_major && ${minor:-0} >= required_minor)))
}

resolve_executable() {
  local value=$1
  if [[ $value == */* ]]; then
    printf '%s\n' "$value"
  else
    command -v "$value" || true
  fi
}

find_toolchain() {
  note "TOOLCHAIN"
  CC_BIN=${CC:-$(command -v gcc || true)}
  CXX_BIN=${CXX:-$(command -v g++ || true)}
  if [[ -n ${CMAKE:-} ]]; then
    CMAKE_BIN=$CMAKE
  elif command -v cmake >/dev/null 2>&1; then
    CMAKE_BIN=$(command -v cmake)
  elif command -v cmake3 >/dev/null 2>&1; then
    CMAKE_BIN=$(command -v cmake3)
  fi

  CC_BIN=$(resolve_executable "$CC_BIN")
  CXX_BIN=$(resolve_executable "$CXX_BIN")
  CMAKE_BIN=$(resolve_executable "$CMAKE_BIN")

  [[ -n $CC_BIN && -x $CC_BIN ]] || die "GCC was not found; load/install GCC 10.3+"
  [[ -n $CXX_BIN && -x $CXX_BIN ]] || die "G++ was not found; load/install GCC 10.3+"
  [[ -n $CMAKE_BIN && -x $CMAKE_BIN ]] ||
    die "CMake was not found; load/install CMake 3.16+"

  local gcc_version gcc_major
  gcc_version=$("$CXX_BIN" -dumpfullversion -dumpversion)
  gcc_major=${gcc_version%%.*}
  [[ $gcc_major =~ ^[0-9]+$ ]] || die "unable to determine G++ version"
  version_at_least "$gcc_version" 10 3 ||
    die "G++ 10.3+ is required; found ${gcc_version}"
  if ((gcc_major == 10)); then
    CXX_COMPAT_FLAGS=(-fcoroutines)
  fi

  printf 'CC:    %s\n' "$CC_BIN"
  printf 'CXX:   %s\n' "$CXX_BIN"
  printf 'CMake: %s\n' "$CMAKE_BIN"
  "$CXX_BIN" --version | sed -n '1p'
  "$CMAKE_BIN" --version | sed -n '1p'

  if ! printf '%s\n' \
    '#include <concepts>' \
    '#include <coroutine>' \
    'static_assert(std::convertible_to<int, long>);' \
    'struct task {' \
    '  struct promise_type {' \
    '    task get_return_object() { return {}; }' \
    '    std::suspend_never initial_suspend() { return {}; }' \
    '    std::suspend_never final_suspend() noexcept { return {}; }' \
    '    void return_void() {}' \
    '    void unhandled_exception() {}' \
    '  };' \
    '};' \
    'task probe() { co_return; }' \
    'int main() { probe(); }' |
    "$CXX_BIN" -std=c++20 "${CXX_COMPAT_FLAGS[@]}" -fopenmp \
      -x c++ -fsyntax-only - \
      >/dev/null 2>&1; then
    die "the selected compiler cannot compile C++20 coroutines with OpenMP"
  fi
}

check_headers() {
  note "DEVELOPMENT HEADERS"
  local headers=(
    infiniband/verbs.h
    rdma/rdma_cma.h
    numa.h
    libmemcached/memcached.h
    boost/program_options.hpp
    fmt/core.h
    cblas.h
    lapacke.h
    libaio.h
  )
  local include_arguments=()
  local include_dir
  if [[ -n $DEPS_DIR ]]; then
    for include_dir in \
      "${DEPS_DIR}/include" \
      "${DEPS_DIR}/include/openblas" \
      "${DEPS_DIR}/include/openblas-pthread" \
      "${DEPS_DIR}/include/aarch64-linux-gnu"; do
      if [[ -d $include_dir ]]; then
        include_arguments+=(-I "$include_dir")
      fi
    done
  fi
  for include_dir in \
    /usr/include/openblas \
    /usr/include/openblas-pthread \
    /usr/include/aarch64-linux-gnu \
    /usr/local/include/openblas; do
    if [[ -d $include_dir ]]; then
      include_arguments+=(-I "$include_dir")
    fi
  done
  local header
  local missing=0
  for header in "${headers[@]}"; do
    if printf '#include <%s>\n' "$header" |
      "$CXX_BIN" -std=c++20 -fopenmp "${include_arguments[@]}" \
        "${CXX_COMPAT_FLAGS[@]}" \
        -x c++ -fsyntax-only - \
        >/dev/null 2>&1; then
      printf 'OK      %s\n' "$header"
    else
      printf 'MISSING %s\n' "$header"
      missing=1
    fi
  done
  ((missing == 0)) ||
    die "development headers are missing; use --deps-dir or ask the administrator for the corresponding -devel packages"
}

read_text_file() {
  local path=$1
  local value
  if [[ ! -r $path ]]; then
    printf 'unknown'
    return
  fi
  if ! value=$(cat -- "$path" 2>/dev/null); then
    printf 'unavailable'
    return
  fi
  printf '%s' "${value//$'\n'/}"
}

check_rdma() {
  note "RDMA / ROCE"
  local port_root="/sys/class/infiniband/${RDMA_DEVICE}/ports/${IB_PORT}"
  [[ -d $port_root ]] || die "RDMA port not found: ${RDMA_DEVICE}/${IB_PORT}"
  printf 'Device/port: %s/%s\n' "$RDMA_DEVICE" "$IB_PORT"
  printf 'State:       %s\n' "$(read_text_file "${port_root}/state")"
  printf 'Link layer:  %s\n' "$(read_text_file "${port_root}/link_layer")"
  grep -q 'ACTIVE' "${port_root}/state" || die "RDMA port is not active"
  grep -qi 'Ethernet' "${port_root}/link_layer" ||
    die "the selected port is not an Ethernet/RoCE port"

  printf '\nGID table:\n'
  local gid_file index gid type netdev
  local gid_count=0
  for gid_file in "${port_root}"/gids/*; do
    [[ -e $gid_file ]] || continue
    index=${gid_file##*/}
    gid=$(read_text_file "$gid_file")
    if [[ ! $gid =~ ^([[:xdigit:]]{4}:){7}[[:xdigit:]]{4}$ ||
      $gid == 0000:0000:0000:0000:0000:0000:0000:0000 ]]; then
      continue
    fi
    type=$(read_text_file "${port_root}/gid_attrs/types/${index}")
    netdev=$(read_text_file "${port_root}/gid_attrs/ndevs/${index}")
    printf '%s gid=%s type=%s netdev=%s\n' "$index" "$gid" "$type" "$netdev"
    gid_count=$((gid_count + 1))
  done
  ((gid_count > 0)) || die "the selected RoCE port has no non-empty GID"

  printf '\nLocal IPv4 addresses:\n'
  ip -4 -o addr show

  # node 0 owns the memcached leader
  if [[ $LOCAL_NODE_ID == 0 ]]; then
    has_local_ipv4 "$LEADER_IP" ||
      die "node 0 does not own the configured memcached leader IP ${LEADER_IP}"
  fi

  # 检查到所有其他节点的路由
  local i peer_ip
  for i in "${!ALL_NODE_IPS[@]}"; do
    ((i == LOCAL_NODE_ID)) && continue
    peer_ip=${ALL_NODE_IPS[$i]}
    printf '\nRoute to node %s (%s):\n' "$i" "$peer_ip"
    ip route get "$peer_ip" ||
      die "there is no route to node $i RoCE IP ${peer_ip}"
    if command -v ping >/dev/null 2>&1; then
      ping -c 1 -W 2 "$peer_ip" >/dev/null 2>&1 ||
        warn "node $i (${peer_ip}) did not answer ping; continue only if ICMP is intentionally blocked"
    fi
  done
}

discover_file() {
  local kind=$1
  local explicit=$2
  if [[ -n $explicit ]]; then
    [[ -f $explicit ]] || die "${kind} file does not exist: ${explicit}"
    printf '%s\n' "$explicit"
    return
  fi

  local exact="${DATASET_DIR}/${kind}.bin"
  if [[ -f $exact ]]; then
    printf '%s\n' "$exact"
    return
  fi

  local matches=()
  local path
  case "$kind" in
    base)
      while IFS= read -r path; do matches+=("$path"); done < <(
        find "$DATASET_DIR" -maxdepth 1 -type f -iname '*base*bin' | sort)
      ;;
    query)
      while IFS= read -r path; do matches+=("$path"); done < <(
        find "$DATASET_DIR" -maxdepth 1 -type f -iname '*query*bin' | sort)
      ;;
    gt)
      while IFS= read -r path; do matches+=("$path"); done < <(
        find "$DATASET_DIR" -maxdepth 1 -type f \
          \( -iname '*gt*bin' -o -iname '*ground*truth*bin' \) | sort)
      ;;
  esac
  ((${#matches[@]} == 1)) || {
    printf 'Candidates for %s:\n' "$kind" >&2
    printf '  %s\n' "${matches[@]:-<none>}" >&2
    die "unable to select one ${kind} file; pass --${kind}-file explicitly"
  }
  printf '%s\n' "${matches[0]}"
}

read_bin_header() {
  local file=$1
  local values rows columns
  values=$(od -An -N8 -tu4 "$file")
  read -r rows columns <<<"$values"
  [[ ${rows:-} =~ ^[0-9]+$ && ${columns:-} =~ ^[0-9]+$ ]] ||
    die "cannot read uint32 row/dimension header from ${file}"
  printf '%s %s\n' "$rows" "$columns"
}

validate_vector_file() {
  local label=$1
  local file=$2
  local rows=$3
  local columns=$4
  local width=$5
  local actual_size expected_size
  actual_size=$(stat -c '%s' "$file")
  expected_size=$((8 + rows * columns * width))
  ((actual_size == expected_size)) ||
    die "${label} size mismatch: got ${actual_size}, expected ${expected_size} bytes"
}

check_dataset() {
  note "DATASET CHECK"
  [[ -d $DATASET_DIR ]] || die "dataset directory does not exist: ${DATASET_DIR}"
  command -v od >/dev/null 2>&1 || die "od is required to inspect bin headers"
  command -v stat >/dev/null 2>&1 || die "stat is required to inspect bin files"

  BASE_FILE=$(discover_file base "$BASE_FILE")
  QUERY_FILE=$(discover_file query "$QUERY_FILE")
  GT_FILE=$(discover_file gt "$GT_FILE")

  read -r BASE_ROWS BASE_DIM <<<"$(read_bin_header "$BASE_FILE")"
  read -r QUERY_ROWS QUERY_DIM <<<"$(read_bin_header "$QUERY_FILE")"

  local gt_header
  read -r GT_ROWS GT_K <<<"$(read_bin_header "$GT_FILE")"

  validate_vector_file base "$BASE_FILE" "$BASE_ROWS" "$BASE_DIM" 4
  validate_vector_file query "$QUERY_FILE" "$QUERY_ROWS" "$QUERY_DIM" 4
  validate_vector_file gt "$GT_FILE" "$GT_ROWS" "$GT_K" 4

  ((BASE_ROWS > 0)) || die "base row count is 0"
  ((BASE_DIM > 0)) || die "base dimension is 0"
  ((QUERY_DIM == BASE_DIM)) || die "query dimension ${QUERY_DIM} does not match base dimension ${BASE_DIM}"
  ((GT_ROWS >= QUERY_ROWS)) || die "GT contains fewer queries than query.bin"
  ((GT_K >= RESULT_K)) || die "GT K=${GT_K} is smaller than requested K=${RESULT_K}"

  local gt_size minimum_gt_size
  gt_size=$(stat -c '%s' "$GT_FILE")
  minimum_gt_size=$((8 + GT_ROWS * GT_K * 4))
  ((gt_size >= minimum_gt_size)) ||
    die "GT file is too short for ${GT_ROWS}x${GT_K} uint32 neighbor IDs"

  MILLION=$(( (BASE_ROWS + 999999) / 1000000 ))

  printf 'Base:  %s (%s x %s float32)\n' "$BASE_FILE" "$BASE_ROWS" "$BASE_DIM"
  printf 'Query: %s (%s x %s float32)\n' "$QUERY_FILE" "$QUERY_ROWS" "$QUERY_DIM"
  printf 'GT:    %s (%s x K=%s)\n' "$GT_FILE" "$GT_ROWS" "$GT_K"
}

check_shared_output() {
  note "OUTPUT PATH"
  mkdir -p "$OUTPUT_DIR"
  [[ -w $OUTPUT_DIR ]] || die "output directory is not writable: ${OUTPUT_DIR}"
  printf 'Output: %s\n' "$OUTPUT_DIR"
  df -T "$OUTPUT_DIR" | sed -n '1,2p'

  local marker="${OUTPUT_DIR}/.cotra-shared-node${LOCAL_NODE_ID}"
  printf 'host=%s node=%s time=%s\n' "$HOST_SHORT" "$LOCAL_NODE_ID" \
    "$(date -Iseconds)" >"$marker"

  local peer_cnt=0
  local i
  for i in "${!ALL_NODE_IPS[@]}"; do
    ((i == LOCAL_NODE_ID)) && continue
    [[ -f ${OUTPUT_DIR}/.cotra-shared-node${i} ]] && peer_cnt=$((peer_cnt + 1))
  done
  if ((peer_cnt == NUM_NODES - 1)); then
    printf 'All %d peer markers visible.\n' "$((NUM_NODES - 1))"
  else
    warn "only ${peer_cnt}/$((NUM_NODES - 1)) peer markers visible; run check on all other nodes first"
  fi
}

run_preflight() {
  validate_arguments
  detect_local_node
  write_config
  note "HOST"
  printf 'Host:       %s\n' "$HOST_SHORT"
  printf 'Node ID:    %s\n' "$LOCAL_NODE_ID"
  printf 'Arch:       %s\n' "$(uname -m)"
  printf 'Config:     %s\n' "$CONFIG_FILE"
  printf 'Build dir:  %s\n' "$BUILD_DIR"
  printf 'Num nodes:  %d\n' "$NUM_NODES"
  [[ $(uname -m) == aarch64 ]] || warn "this script was designed for the reported aarch64 hosts"
  find_toolchain
  check_headers
  check_rdma
  check_dataset
  check_shared_output
  note "PREFLIGHT COMPLETE"
  printf 'Node %s is ready for mode %s.\n' "$LOCAL_NODE_ID" "$MODE"
}

configure_and_build() {
  run_preflight
  note "CMAKE CONFIGURE"
  if [[ -f ${BUILD_DIR}/CMakeCache.txt ]]; then
    local cached_machine_count
    cached_machine_count=$(
      sed -n 's/^COTRA_MACHINE_NUM:STRING=//p' "${BUILD_DIR}/CMakeCache.txt")
    if [[ -n $cached_machine_count && $cached_machine_count != $NUM_NODES ]]; then
      die "existing build directory was configured for ${cached_machine_count} nodes; choose a new --build-dir"
    fi
  fi
  local cmake_extra=()
  if [[ -n $DEPS_DIR ]]; then
    cmake_extra+=(
      "-DCMAKE_INCLUDE_PATH=${DEPS_DIR}/include;${DEPS_DIR}/include/openblas;${DEPS_DIR}/include/openblas-pthread;${DEPS_DIR}/include/aarch64-linux-gnu"
      "-DCMAKE_LIBRARY_PATH=${DEPS_DIR}/lib64"
    )
    # 帮助 find_package(Boost/fmt/OpenBLAS 等) 定位 deps 目录
    cmake_extra+=("-DCMAKE_PREFIX_PATH=${DEPS_DIR}")
    # FindBoost.cmake 兜底 hints：如果系统装了另一版本 boost 但没装 devel，
    # 就强制指向 deps 目录，避免它找到 /usr/include/boost 但找不到 .so
    # CMake 3.29+ 需要 <PkgName>_ROOT（驼峰）且 CMP0144 NEW 才能用，
    # 但 <PKG>_ROOT（全大写）老版本 FindBoost.cmake 也认，同时传一份。
    if [[ -d ${DEPS_DIR}/include/boost ]]; then
      cmake_extra+=("-DBoost_ROOT=${DEPS_DIR}")
      cmake_extra+=("-DBOOST_ROOT=${DEPS_DIR}")
      cmake_extra+=("-DBOOST_INCLUDEDIR=${DEPS_DIR}/include")
      cmake_extra+=("-DBOOST_LIBRARYDIR=${DEPS_DIR}/lib64")
      cmake_extra+=("-DBoost_NO_SYSTEM_PATHS=ON")
      # FindBoost.cmake (before 3.30) 仍然认老拼写，也保持传递
      cmake_extra+=("-DBoost_INCLUDE_DIR=${DEPS_DIR}/include")
      cmake_extra+=("-DBoost_LIBRARY_DIR_RELEASE=${DEPS_DIR}/lib64")
    fi
    # 让 linker 知道 rpath，同时环境变量 LDFLAGS 兜底
    local deps_rpath="-Wl,-rpath,${DEPS_DIR}/lib64"
    cmake_extra+=(
      "-DCMAKE_BUILD_RPATH=${DEPS_DIR}/lib64"
      "-DCMAKE_INSTALL_RPATH=${DEPS_DIR}/lib64"
      "-DCMAKE_SKIP_BUILD_RPATH=OFF"
      "-DCMAKE_BUILD_WITH_INSTALL_RPATH=ON"
      "-DCMAKE_EXE_LINKER_FLAGS=${deps_rpath} ${CMAKE_EXE_LINKER_FLAGS:-}"
      "-DCMAKE_SHARED_LINKER_FLAGS=${deps_rpath} ${CMAKE_SHARED_LINKER_FLAGS:-}"
    )
    export LDFLAGS="${deps_rpath} ${LDFLAGS:-}"
  fi
  local lat_cmake=()
  if (( ENABLE_LAT )); then
    lat_cmake=(-DCOTRA_LAT=ON)
  fi
  "$CMAKE_BIN" -S "$REPO_ROOT" -B "$BUILD_DIR" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_C_COMPILER="$CC_BIN" \
    -DCMAKE_CXX_COMPILER="$CXX_BIN" \
    -DCOTRA_MACHINE_NUM=$NUM_NODES \
    -DCOTRA_MAX_THREAD_NUM=$MAX_THREAD_NUM \
    "${lat_cmake[@]}" \
    "${cmake_extra[@]}"

  note "BUILD"
  "$CMAKE_BIN" --build "$BUILD_DIR" -j "$BUILD_JOBS"
  [[ -x ${BUILD_DIR}/tests/scala_index ]] || die "scala_index was not built"
  [[ -x ${BUILD_DIR}/tests/scala_anns ]] || die "scala_anns was not built"
  printf 'Build completed on node %s.\n' "$LOCAL_NODE_ID"
}

runtime_preflight() {
  run_preflight
  [[ -x ${BUILD_DIR}/tests/scala_index ]] ||
    die "scala_index is missing; run this script in build mode on this node first"
  [[ -x ${BUILD_DIR}/tests/scala_anns ]] ||
    die "scala_anns is missing; run this script in build mode on this node first"
  local locked
  locked=$(ulimit -l)
  [[ $locked == unlimited ]] ||
    die "max locked memory must be unlimited for this first RDMA run; found ${locked}"

  # ------------------------------------------------------------------
  # Runtime shared-library search order (most reliable first match wins):
  #   1. DEPS_DIR/lib64 (boost/fmt/openblas/numa/rdmacm/... self-bundled)
  #   2. Well-known system runtime dirs on Kylin V10 aarch64
  #      (gcc libgfortran / libquadmath / libibverbs are often placed
  #       directly in /usr/lib64, sometimes only under gcc dirs or the
  #       multiarch tuples; listing them explicitly avoids silent
  #       mismatches between ld.so.conf + ldconfig cache across nodes.)
  #   3. Whatever the user already exported in LD_LIBRARY_PATH.
  # ------------------------------------------------------------------
  local _sys_paths=(
    /usr/lib64
    /lib64
    /usr/lib/aarch64-linux-gnu
    /lib/aarch64-linux-gnu
    /usr/lib/gcc/aarch64-linux-gnu/10
    /usr/lib/gcc/aarch64-linux-gnu/10.3.0
    /usr/local/lib64
  )
  local _ld=""
  if [[ -n $DEPS_DIR && -d ${DEPS_DIR}/lib64 ]]; then
    _ld="${DEPS_DIR}/lib64"
  fi
  for p in "${_sys_paths[@]}"; do
    [[ -d $p ]] || continue
    if [[ -n $_ld ]]; then
      _ld="${_ld}:${p}"
    else
      _ld="${p}"
    fi
  done
  if [[ -n ${LD_LIBRARY_PATH:-} ]]; then
    _ld="${_ld}:${LD_LIBRARY_PATH}"
  fi
  if [[ -n $_ld ]]; then
    export LD_LIBRARY_PATH="$_ld"
  fi

  # ------------------------------------------------------------------
  # Verify scala_index/scala_anns can resolve ALL their NEEDED entries
  # right now before starting a long-running job (segfault / exit 127
  # only once the RDMA barrier starts is very costly for 8-node runs).
  # "ldd -r" also triggers IFUNC resolution so we catch ifunc-based
  # libc symbol issues too.
  # ------------------------------------------------------------------
  local _bin _missing
  for _bin in \
    "${BUILD_DIR}/tests/scala_index" \
    "${BUILD_DIR}/tests/scala_anns"
  do
    _missing=$(LD_LIBRARY_PATH="$LD_LIBRARY_PATH" ldd -r "$_bin" 2>&1 \
               | awk '/not found/{print $1}' | sort -u | tr '\n' ' ')
    if [[ -n ${_missing// } ]]; then
      die "Runtime libraries missing for ${_bin} (${HOSTNAME} node ${LOCAL_NODE_ID}): ${_missing}.
  Fix: either install the corresponding rpm package on this node,
  or (preferred) copy those .so files from the leader (agent-21) into
  --deps-dir/lib64 then rsync --deps-dir to all nodes.
  Typical missing deps on fresh runtime nodes:
    libgfortran.so.4   (from gcc-gfortran runtime, needed by OpenBLAS)
    libquadmath.so.0   (from libquadmath runtime, GCC 10 companion)
    libibverbs.so.1    (from rdma-core libibverbs)
    librdmacm.so.1     (from rdma-core librdmacm)
    libmemcached.so.11 (from libmemcached)
    libboost_*.so.1.66.0 (regex/serialization/iostreams/...).
  Then re-run the deployment step."
    fi
  done

  local omp_threads=$RDMA_THREADS
  if [[ $MODE == index ]]; then
    omp_threads=$INDEX_THREADS
  fi
  export OMP_NUM_THREADS=$omp_threads
  export OMP_THREAD_LIMIT=$omp_threads
  export OMP_DYNAMIC=FALSE
  export OMP_PROC_BIND=FALSE
  unset GOMP_CPU_AFFINITY
  export OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-$omp_threads}
}

reset_metadata() {
  # shellcheck source=scripts/restart_memcache.sh
  source "${SCRIPT_DIR}/restart_memcache.sh"
  clear_memcache "$CONFIG_FILE"
}

rdma_arguments() {
  RDMA_ARGS=(
    -d "$RDMA_DEVICE"
    --ib-port "$IB_PORT"
    --barrier-timeout "$BARRIER_TIMEOUT"
  )
  if [[ -n $GID_INDEX ]]; then
    RDMA_ARGS+=(--gid-index "$GID_INDEX")
  fi
}

print_command() {
  printf 'Command:'
  printf ' %q' "$@"
  printf '\n'
}

run_index() {
  runtime_preflight
  reset_metadata
  rdma_arguments
  local log_file="${OUTPUT_DIR}/index-node${LOCAL_NODE_ID}.log"
  local command=(
    "${BUILD_DIR}/tests/scala_index"
    --config_file "$CONFIG_FILE"
    --graph_type "$GRAPH_TYPE"
    --data_type "$DATA_TYPE"
    --dist_fn "$DISTANCE"
    --data_path "$BASE_FILE"
    --index_path_prefix "${OUTPUT_DIR}/merged_index"
    -R "$MAX_DEGREE"
    -L "$BUILD_L"
    -B "$SEARCH_DRAM_GB"
    -M "$BUILD_DRAM_GB"
    -T "$INDEX_THREADS"
    -t "$RDMA_THREADS"
    -s "$MILLION"
    --scala_v3
    --scalagraph_v2
    "${RDMA_ARGS[@]}"
  )
  note "${NUM_NODES}-NODE INDEX BUILD"
  printf 'Start node 0 first, then nodes 1..%d. Log: %s\n' \
    "$((NUM_NODES - 1))" "$log_file"
  print_command "${command[@]}"
  if "${command[@]}" 2>&1 | tee "$log_file"; then
    printf 'Index build completed successfully on node %s.\n' "$LOCAL_NODE_ID"
  else
    local status=${PIPESTATUS[0]}
    printf 'Index build failed on node %s with status %s.\n' \
      "$LOCAL_NODE_ID" "$status" >&2
    return "$status"
  fi
}

run_search() {
  runtime_preflight
  local required_index="${OUTPUT_DIR}/merged_index${LOCAL_NODE_ID}_final_scala.index"
  [[ -f $required_index ]] ||
    die "local index is missing: ${required_index}; finish index mode on all nodes first"
  reset_metadata
  rdma_arguments
  local log_file="${OUTPUT_DIR}/search-node${LOCAL_NODE_ID}.log"
  local command=(
    "${BUILD_DIR}/tests/scala_anns"
    --config_file "$CONFIG_FILE"
    --app_type "$APP_TYPE"
    --graph_type "$GRAPH_TYPE"
    --data_type "$DATA_TYPE"
    --dist_fn "$DISTANCE"
    --data_path "$BASE_FILE"
    --query_path "$QUERY_FILE"
    --gt_path "$GT_FILE"
    --query_size "${RESULT_QSIZE:-$QUERY_ROWS}"
    --res_knn "$RESULT_K"
    --index_path_prefix "${OUTPUT_DIR}/merged_index"
    -R "$MAX_DEGREE"
    -L "$BUILD_L"
    -B "$SEARCH_DRAM_GB"
    -M "$BUILD_DRAM_GB"
    -T "$INDEX_THREADS"
    -t "$RDMA_THREADS"
    -s "$MILLION"
    --scala_v3
    "${RDMA_ARGS[@]}"
  )
  note "${NUM_NODES}-NODE SEARCH"
  printf 'Start node 0 first, then nodes 1..%d. Log: %s\n' \
    "$((NUM_NODES - 1))" "$log_file"
  print_command "${command[@]}"
  if "${command[@]}" 2>&1 | tee "$log_file"; then
    printf 'Search completed successfully on node %s.\n' "$LOCAL_NODE_ID"
  else
    local status=${PIPESTATUS[0]}
    printf 'Search failed on node %s with status %s.\n' \
      "$LOCAL_NODE_ID" "$status" >&2
    return "$status"
  fi
}

case "$MODE" in
  check)
    run_preflight
    ;;
  build)
    configure_and_build
    ;;
  index)
    run_index
    ;;
  search)
    run_search
    ;;
esac
